(define-module (automate overrides)
  #:use-module (gnu packages boost)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages libedit)
  #:use-module (gnu packages backup)
  #:use-module (gnu packages crypto)
  #:use-module (gnu packages bdw-gc)
  #:use-module (gnu packages version-control)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages markup)
  #:use-module (gnu packages cpp)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages sqlite)
  #:use-module (gnu packages hardware)
  #:use-module (gnu packages bison)
  #:use-module (gnu packages cmake)
  #:use-module (gnu packages compiler-tools)
  #:use-module (gnu packages check)
  #:use-module (gnu packages web)
  #:use-module (gnu packages man)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages databases)
  #:use-module (gnu packages pkg-config)
  #:use-module (guix utils)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (guix git-download)
  #:use-module (guix build-system meson)
  #:use-module ((guix licenses) #:prefix license:))
