name: Test and build
run-name: Test and build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-

      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1

      - name: Ensure no locale warning
        run: test -z "$(guix --version 2>&1 >/dev/null)"

      - name: install dependencies
        run: guix shell -m manifest.scm

      - name: make check
        run: make check


